openapi: "3.0.0"
info:
  version: 1.0.0
  title: Sample API
  license:
    name: MIT
components:
  schemas:
    User:
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
    UserExtend:
      allOf:
        - $ref: '#/components/schemas/User'
        - type: object
          properties:
            email:
              type: string
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: string
          format: int32
        message:
          type: string
  responses:
    Error:
      description: error response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
paths:
  /user:
    get:
      summary: get user
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        default:
          $ref: '#/components/responses/Error'
  /userExtend:
    get:
      summary: get user
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserExtend'
        default:
          $ref: '#/components/responses/Error'

